apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  # The name must match the VirtualMachine you are patching
  name: fedora-dev-vms
spec:
  # 1. Update storageClassName within the first DataVolumeTemplate
  dataVolumeTemplates:
    - metadata:
        name: fedora-bana-tapir-92-volume
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
          # --- TARGET 1: New Storage Class Name ---
          storageClassName: "synology-iscsi-storage" # <-- REPLACE with your actual StorageClass name