apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  # The name must match the VirtualMachine you are patching
  name: fedora-dev-vms
spec:
  # --- TARGET 1: Network Interface and Network Definition Names ---
  template:
    spec:
      domain:
        devices:
          interfaces:
            - model: virtio
              name: bridge-network-vlan50 # Ensure this name matches the network interface to be patched
              state: up
              bridge: {}
      networks:
      - name: bridge-network-vlan50 # Ensure this name matches the network interface to be patched
        multus:
          # --- TARGET 2: New Network Attachment Definition Name ---
          networkName: "bridge-network-vlan50" # <-- REPLACE with your actual `namespace/networkName`