apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  name: dev-fedora-vms
spec:
  replicas: 1
  selector:
    matchLabels:
      kubevirt.io/vmpool: dev-fedora-vms
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: dev-fedora-vms
    spec:
      dataVolumeTemplates:
      - metadata:
          name: fedora-dev-volume
        spec:
          sourceRef:
            kind: DataSource
            name: fedora
            namespace: openshift-virtualization-os-images
          storage:
            resources:
              requests:
                storage: 30Gi
            storageClassName: synology-iscsi-storage
      runStrategy: Always
      template:
        metadata:
          labels:
            kubevirt.io/vmpool: dev-fedora-vms
        spec:
          domain:
            cpu:
              cores: 1
            devices:
              disks:
              - disk:
                  bus: virtio
                name: rootdisk
              - disk:
                  bus: virtio
                name: cloudinitdisk
              interfaces:
              - bridge: {}
                model: virtio
                name: net-vlan50
              rng: {}
            memory:
              guest: 1024M
          networks:
          - multus:
              networkName: default/bridge-network-vlan50
            name: net-vlan50
          volumes:
          - dataVolume:
              name: fedora-dev-volume
            name: rootdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                users:
                - name: rguske
                  gecos: R. Guske
                  groups: wheel
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  shell: /bin/bash
                  ssh_authorized_keys:
                    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINGf2ipOy2h3lJHbwP3qm4yICHvEFvYjlZGHWsEEUHCl jarvishomelab@gmail.com
            name: cloudinitdisk
