apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-kubevirt-pool-manager
  namespace: rguske-dev-fedora-vms
  labels:
    app.kubernetes.io/managed-by: argocd
rules:
- apiGroups:
  - pool.kubevirt.io
  resources:
  - virtualmachinepools
  verbs:
  - create
  - get
  - update
  - delete
  - patch
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-bind-kubevirt-pool-manager
  namespace: rguske-dev-fedora-vms
  labels:
    app.kubernetes.io/managed-by: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-kubevirt-pool-manager
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops